### ISSUE TITLE
Inicio do programa

### ISSUE THREAD

**Issue by rcatechnology** [Cruzeta00/GuessTheNumber#1]
Ao abrir o programa pela primeira vez, ele solicita para digitar 1 para começar.
O ideal seria não fazer essa solicitação e já solicitar as dificuldades.

![image](https://user-images.githubusercontent.com/54815598/125509967-879cd620-35dc-4e13-804c-a64701c575f7.png)

Ideal:

![image](https://user-images.githubusercontent.com/54815598/125510130-b14ad83e-95a1-48db-aa50-9326aafef3a1.png)

**Comment by Cruzeta00** [comment]
Feito.
