### ISSUE TITLE
Começando o jogo

### ISSUE THREAD

**Issue by rcatechnology** [Cruzeta00/GuessTheNumber#2]
Ao iniciar o jogo, deve ter um retorno para o usuário, por exemplo: "Pensei no número entre XXXXX e YYYYYY, tente adivinhar!!"

![image](https://user-images.githubusercontent.com/54815598/125510370-19c7a7e3-0b1c-4356-9ced-913e0f645e84.png)

Ao selecionar recomeçar o jogo novamente, também apresentar a mensagem.
![image](https://user-images.githubusercontent.com/54815598/125510597-f3fabebc-d59e-4e26-a7cc-8cf3b6bb1988.png)

**Comment by rcatechnology** [comment]
Ideal seria mostrar quanto tempo o usuário terá para resolver também.

**Comment by Cruzeta00** [comment]
Junto da issue#1, já contemplada.
