### ISSUE TITLE
Ganhando o jogo

### ISSUE THREAD

**Issue by rcatechnology** [Cruzeta00/GuessTheNumber#4]
A mensagem final, "Parabéns!!! VocÊ acertou......" Ficou muito ambigua.
Um total de XX segundos quer dizer o que? Faltando? Total de tempo que eu usei? Qual era o tempo total?

![image](https://user-images.githubusercontent.com/54815598/125510771-c95deee8-74af-47cf-a5e1-3d83747f52bf.png)

**Comment by Cruzeta00** [comment]
Feito.
