### ISSUE TITLE
Ganhando

### ISSUE THREAD

**Issue by rcatechnology** [Cruzeta00/GuessTheNumber#7]
Ao ganhar, aparece o tempo de alguma coisa.
Trazer somente o numero inteiro (arredondar o valor de segundos para cima ou para baixo usando a regra do 0,5)
![image](https://user-images.githubusercontent.com/54815598/125512373-674dae7f-6e5d-4ef7-adba-5c1fa77a1ffc.png)

**Comment by Cruzeta00** [comment]
Feito.
